name: actiontest

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: autoever1
      REPO: actiontest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15

      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Docker Build and push
        run:
          docker buildx build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:latest
          docker push
