name: actiontest

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: autoever1
      REPO: actiontest
    steps:
      - uses: actions/checkout@v4 # 최신 버전 권장
      - name: Set up Go
        uses: actions/setup-go@v5 # 최신 버전 권장
        with:
          go-version: '1.15'

      - name: DockerHub Login
        uses: docker/login-action@v3 # 최신 버전 권장
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}

      - name: Build and Push Docker image # 이 스텝으로 변경해야 합니다.
        uses: docker/build-push-action@v5 # docker buildx 오류를 해결하는 핵심입니다.
        with:
          context: . # Dockerfile이 있는 현재 디렉토리를 빌드 컨텍스트로 사용
          push: true # Docker Hub로 이미지를 푸시하도록 설정
          tags: ${{ env.NAME }}/${{ env.REPO }}:latest # 푸시할 이미지 태그 명시
